name: Update banner data
on:
  schedule:
  - cron: "15 10 * * 2"
  workflow_dispatch: { }
jobs:
  update_banners:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - name: Build banners
      run: |
        npm run build-banners --silent > >(tee '~output') &&
        (
          echo $'Automated update\n\nBuild output:\n\n~~~diff'
          sed -e 's/\x1b\[[0-9;]*m//g' '~output'
          echo '~~~'
        ) > '~body'
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: site/banners.json
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit-message: "chore: update banners.json"
        branch: auto-update-banners
        title: Update banners.json
        body-path: "~body"
