name: Update banner data
on:
  schedule:
    - cron: 0 4 * * 2,3
  workflow_dispatch: { }
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build-banners
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        title: Update banners.json
        commit-message: Update banners.json
        branch: auto-update-banners
